Neos:
  Flow:
    mvc:
      routes:
        'Flownative.OAuth2.Client': true
        'Neos.Flow':
          'position': 'after Flownative.OAuth2.Client'

Flownative:
  OAuth2:
    Client:
      services: []
#        - name: 'flownative-beach'
#          className: 'Flownative\Beach\BeachClient'
