Neos:
  Flow:
    mvc:
      routes:
        'Flownative.OAuth2.Client':
          'position': 'after Neos.Flow'

Flownative:
  OAuth2:
    Client:
      services: []
#        - name: 'flownative-beach'
#          className: 'Flownative\Beach\BeachClient'
